language: node_js
dist: trusty
sudo: required
node_js:
  - '8'
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?$/
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.22.0
    - COMPOSE_FILE=docker-compose.0_11.yml
    - KAFKA_VERSION=0.11
before_install:
  - bash ./scripts/shouldRunTests.sh && SKIP_TESTS=true && echo "Only non-code has changed!" || test true
  - test $SKIP_TESTS && echo "Skipped!" || sudo rm /usr/local/bin/docker-compose
  - test $SKIP_TESTS && echo "Skipped!" || curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - test $SKIP_TESTS && echo "Skipped!" || chmod +x docker-compose
  - test $SKIP_TESTS && echo "Skipped!" || sudo mv docker-compose /usr/local/bin
  - test $SKIP_TESTS && echo "Skipped!" || curl -o- -L https://yarnpkg.com/install.sh | bash
  - test $SKIP_TESTS && echo "Skipped!" || export PATH=$HOME/.yarn/bin:$PATH
install:
  - test $SKIP_TESTS && echo "Skipped!" || yarn install
jobs:
  include:
    - stage: test
      name: 'Lint'
      script:
        - env
        - test $SKIP_TESTS && echo "Skipped!" || yarn lint
    - stage: test
      name: 'Broker'
      script:
        - env
        - test $SKIP_TESTS && echo "Skipped!" || docker-compose -f ${COMPOSE_FILE} pull
        - test $SKIP_TESTS && echo "Skipped!" || yarn test:group:broker:ci
    - stage: test
      name: 'Admin'
      script:
        - env
        - test $SKIP_TESTS && echo "Skipped!" || docker-compose -f ${COMPOSE_FILE} pull
        - test $SKIP_TESTS && echo "Skipped!" || yarn test:group:admin:ci
    - stage: test
      name: 'Producer'
      script:
        - env
        - test $SKIP_TESTS && echo "Skipped!" || docker-compose -f ${COMPOSE_FILE} pull
        - test $SKIP_TESTS && echo "Skipped!" || yarn test:group:producer:ci
    - stage: test
      name: 'Consumer'
      script:
        - env
        - test $SKIP_TESTS && echo "Skipped!" || docker-compose -f ${COMPOSE_FILE} pull
        - test $SKIP_TESTS && echo "Skipped!" || yarn test:group:consumer:ci
    - stage: test
      name: 'Others (protocol, cluster, network, etc)'
      script:
        - env
        - test $SKIP_TESTS && echo "Skipped!" || docker-compose -f ${COMPOSE_FILE} pull
        - test $SKIP_TESTS && echo "Skipped!" || yarn test:group:others:ci
    - stage: deploy
      name: NPM release
      sudo: false
      node_js: "8"
      script: skip
      before_install: skip
      install: skip
      deploy:
        provider: npm
        email: ornelas.tulio@gmail.com
        api_key:
          secure: jCFJrd4NaE65EziOKK8CpeINNTBRXP5chJ80FfFFsp5Er2fWpKqIiyOJTZk1OzlDhwmMRM9mwE7zcm4uL4a6pkPCOUvjRw1qdCB6YM68IzBzLx8u2romurv6OsbrPdcBdvacNFht4lw5slqhyxZTE7vZFP4t98fjHdRnPoW0w08OZUt8I3kPOpleGUAzWFO6zmIgNql1HgyOo6YWzRDGPu1Utm20mdSrzmGplbk5i2gKH/EBR2zjWoB9SRy7+7KL0qT44/8yJeyppiFAbv3PFqbJEUMJENTeP1SkPatcck78wAhGMb60WuWcd2mRGClkt3SDUFiL2egEdEo4Ot4YspOE9R3P++10c1dAWnDrmcrUMrxKibWzxoJoynl/p4FO3VyWf8ibePRUWwmrVgFuFlykalMXdVZZo1UoTIzl7pYx8tiwHCxqHPKPcFOQMJWIZCo5xyKUhjvWPS6bwOIsBRs4O4y6DUMFlwVXl7kmQwa3Z9h2Jkfa4lOksbMTuc8LLM0xAU/+vmApuZquNJLsAlweDzaI7pn+RuUREUXCDSUFn0K5CPni1uSUCKu1rNnTqsMPRbmXPlpr+1rhqZOPmavo6Zma9hjNxWCIO/OA9RoKSsvE6AhUALJbsz/1I25+6mgNIYz6r107tZe/8AbIatVquJ6hB4hNrHI+21HTpv8=
        on:
          tags: true
          repo: tulios/kafkajs
    - stage: deploy
      name: Website
      sudo: false
      script:
        - '[[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]] && SHOULD_DEPLOY=true || echo "Skipping deploy"'
        - 'test $SHOULD_DEPLOY && git config --global user.name "${GH_NAME}" || test true'
        - 'test $SHOULD_DEPLOY && git config --global user.email "${GH_EMAIL}" || test true'
        - 'test $SHOULD_DEPLOY && echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc || test true'
        - 'test $SHOULD_DEPLOY && cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages || test true'