version: '2'
services:
  zk:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      JMX_OPTS: "-Djava.security.auth.login.config=/etc/kafka/server-jaas.conf"
    volumes:
      - ./testHelpers/kafka/server-jaas.conf:/etc/kafka/server-jaas.conf
  kafka1:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093,SASL_SSL://:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9092,SSL://${HOST_IP}:9093,SASL_SSL://${HOST_IP}:9094"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "testtest"
      KAFKA_SSL_KEY_PASSWORD: "testtest"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "testtest"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/server-jaas.conf"
      KAFKA_CREATE_TOPICS: "topic-test:6:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testHelpers/certs:/var/private/ssl/certs
      - ./testHelpers/kafka/server-jaas.conf:/opt/kafka/config/server-jaas.conf
      # - ./testHelpers/kafka/log4j.properties:/opt/kafka/config/log4j.properties
  kafka2:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9095:9095"
      - "9096:9096"
      - "9097:9097"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9095,SSL://:9096,SASL_SSL://:9097"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9095,SSL://${HOST_IP}:9096,SASL_SSL://${HOST_IP}:9097"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "testtest"
      KAFKA_SSL_KEY_PASSWORD: "testtest"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "testtest"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/server-jaas.conf"
      KAFKA_CREATE_TOPICS: "topic-test:6:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testHelpers/certs:/var/private/ssl/certs
      - ./testHelpers/kafka/server-jaas.conf:/opt/kafka/config/server-jaas.conf
      # - ./testHelpers/kafka/log4j.properties:/opt/kafka/config/log4j.properties
  kafka3:
    image: wurstmeister/kafka:0.10.2.1
    ports:
      - "9098:9098"
      - "9099:9099"
      - "9100:9100"
    links:
      - zk
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LISTENERS: "PLAINTEXT://:9098,SSL://:9099,SASL_SSL://:9100"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP}:9098,SSL://${HOST_IP}:9099,SASL_SSL://${HOST_IP}:9100"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "testtest"
      KAFKA_SSL_KEY_PASSWORD: "testtest"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/certs/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "testtest"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN,SCRAM-SHA-256,SCRAM-SHA-512"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/config/server-jaas.conf"
      KAFKA_CREATE_TOPICS: "topic-test:6:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./testHelpers/certs:/var/private/ssl/certs
      - ./testHelpers/kafka/server-jaas.conf:/opt/kafka/config/server-jaas.conf
      # - ./testHelpers/kafka/log4j.properties:/opt/kafka/config/log4j.properties
